
# ----------------------------------------------------------------------
# General
# ----------------------------------------------------------------------

GLOBAL_NAME: default
USE_GPU: True

# ----------------------------------------------------------------------
# Datasets
# ----------------------------------------------------------------------


# ----------------------------------------------------------------------
# Feature generation
# ----------------------------------------------------------------------

FEAT:
  NAME: default
  RECALC: False


# ----------------------------------------------------------------------
# Label generation
# ----------------------------------------------------------------------
LABEL:
  NAME: default
  RECALC: False


# ----------------------------------------------------------------------
# Training
# ----------------------------------------------------------------------
TRAIN:
  NAME: default
  RECALC: False



# ----------------------------------------------------------------------
# Evaluation
# ----------------------------------------------------------------------
EVAL:
  BATCHSIZE: 1


